let singleEditprop = {
  advanceAmount: null,
  agentId: null,
  amenities: ["Parking slot", "CCTV"],
  area: "Salzburg",
  availability: null,
  bathrooms: 2,
  bedrooms: 2,
  country: "United States",
  createdAt: "2025-10-30T07:30:40.000Z",
  currency: null,
  description: "description for the property",
  facing: null,
  floorNo: null,
  furnishing: "",
  id: 158,
  images: [{ id: 633, image: "/api/uploads/1761809440970-villa-1-main.jpg" }],
  isAssigned: false,
  isVerified: false,
  is_listed: false,
  latitude: 17.3945522,
  location: "Hyderabad",
  longitude: 78.4551163,
  maintenance: null,
  monthsAdvance: null,
  nearbyHospital: null,
  nearbyMalls: null,
  nearbyParks: null,
  nearbySchool: null,
  ownerId: 46,
  projectName: "Aparna Yellow bells",
  propertyAge: null,
  propertyLength: null,
  propertyStatus: "In Progress",
  propertyType: "Commercial",
  reason: null,
  rentAmount: "3444.00",
  rentType: "Daily",
  totalFloors: null,
  updatedAt: "2025-10-30T07:30:40.000Z",
};
